[2022-02-17 01:15:19,779] -- [ERROR][30]--[Test.tests_for_API.conftest->tests_for_API]: 
Pet hasn't been found by ID, status code -> 404
